# Quantum information tools

<em style="color:gray;">Copyright (c) 2024 QuAIR team. All Rights Reserved.</em>

This tutorial introduces the `qinfo` module in QuAIRKit. The functions in `quairkit.qinfo` can be categorized into several application areas relevant to quantum computation and quantum information. For quantum computation, there are functions mainly to compute the Kronecker product, conjugate transpose, and trace of matrices. There are also functions associated with quantum gates, such as decomposing a single-qubit unitary operation into rotation angles around the Z and Y axes. For functions related to quantum information theory, this module includes partial trace, quantum entropies, the fidelity of quantum states, various kinds of norms, and so on. Additionally, this module provides data format validation such as verifying whether a matrix is a unitary, density matrix, or a projector. 

**Table of Contents**
- [Functions in quantum computation](#Functions-in-quantum-computation)
- [Functions in quantum information](#Functions-in-quantum-information)
- [Validation functions](#Validation-functions)
- [Compatibility with different data formats](#Compatibility-with-different-data-formats)


In [1]:
import quairkit as qkit
from quairkit import to_state
from quairkit.database import *
from quairkit.qinfo import *

qkit.set_dtype("complex128")

## Functions in quantum computation
First, initialize two random unitary matrices through a built-in function of QuAIRKit. The matrix A and B are both in *torch.tensor* format.

In [2]:
A = random_unitary(num_qubits=1)
B = random_unitary(num_qubits=1)
print(f"Matrix A is:\n{A}\n")
print(f"Matrix B is:\n{B}")

Matrix A is:
tensor([[ 0.5055-0.1762j, -0.4898+0.6881j],
        [-0.7566-0.3755j, -0.5289+0.0833j]])

Matrix B is:
tensor([[-0.8704-0.4277j,  0.2176+0.1102j],
        [ 0.2255+0.0930j,  0.8921+0.3803j]])


Users can use functions in `qinfo` to implement specific operations on these two matrices.
- Calculate the trace of a matrix by `trace`.
- Calculate the direct sum of matrix A and B with `direct_sum`. Direct sum is an operation that combines two matrices into a larger matrix where 
A and B occupy diagonal blocks of the resulting matrix, and the remaining entries are zero.
- Calculate the Kronecker products of at least two matrices by `NKron`.
- Implement conjugate transpose of a matrix by `dagger`.
- Decompose a single-qubit unitary operator into Z-Y-Z rotation angles by `decomp_1qubit`.
- ...

In [3]:

print(f"The trace of matrix A is {trace(A)}")

print(f"The direct sum of matrix A and B is: \n{direct_sum(A,B)}\n")

print(f"The tensor product of matrix A and B is: \n{NKron(A,B)}\n")

print(f"The conjugate transpose of matrix A is: \n{dagger(A)}\n")

print(f"The decomposition of single-qubit unitary operator A to Z-Y-Z rotation angles is {decomp_1qubit(A)}")

The trace of matrix A is (-0.023323571515555197-0.09297417506081378j)
The direct sum of matrix A and B is: 
tensor([[ 0.5055-0.1762j, -0.4898+0.6881j,  0.0000+0.0000j,  0.0000+0.0000j],
        [-0.7566-0.3755j, -0.5289+0.0833j,  0.0000+0.0000j,  0.0000+0.0000j],
        [ 0.0000+0.0000j,  0.0000+0.0000j, -0.8704-0.4277j,  0.2176+0.1102j],
        [ 0.0000+0.0000j,  0.0000+0.0000j,  0.2255+0.0930j,  0.8921+0.3803j]])

The tensor product of matrix A and B is: 
tensor([[-0.5154-0.0628j,  0.1294+0.0173j,  0.7206-0.3895j, -0.1824+0.0958j],
        [ 0.1304+0.0073j,  0.5180+0.0350j, -0.1744+0.1096j, -0.6986+0.4276j],
        [ 0.4979+0.6504j, -0.1233-0.1651j,  0.4959+0.1537j, -0.1243-0.0401j],
        [-0.1357-0.1550j, -0.5322-0.6227j, -0.1270-0.0304j, -0.5035-0.1269j]])

The conjugate transpose of matrix A is: 
tensor([[ 0.5055+0.1762j, -0.7566+0.3755j],
        [-0.4898-0.6881j, -0.5289-0.0833j]])

The decomposition of single-qubit unitary operator A to Z-Y-Z rotation angles is (tensor(-2

## Functions in quantum information
Users can use functions in `qinfo` to quantify information-theoretic properties of quantum states.
- Calculate the von-Neumann entropy of a quantum state by `von_neumann_entropy`.
- Calculate the trace distance of two quantum states by `trace_distance`.
- Calculate the fidelity of two quantum states by `state_fidelity`.
- Calculate the purity of a quantum state by `purity`.
- Calculate the relative entropy of two quantum states by `relative_entropy`.
- Calculate of Schatten p-norm by `p_norm`.
- ...

In [4]:
state1 =  random_state(2).density_matrix
print(f"The first quantum state is:\n {state1}\n")
state2 = random_state(2, rank=1).ket
print(f"The second quantum state is:\n {state2}")

The first quantum state is:
 tensor([[ 0.3507+0.0000j, -0.0197-0.0064j, -0.0641-0.0233j, -0.0154-0.0243j],
        [-0.0197+0.0064j,  0.3630+0.0000j, -0.0631+0.0716j,  0.0748-0.1107j],
        [-0.0641+0.0233j, -0.0631-0.0716j,  0.1179+0.0000j,  0.0061+0.0327j],
        [-0.0154+0.0243j,  0.0748+0.1107j,  0.0061-0.0327j,  0.1684+0.0000j]])

The second quantum state is:
 tensor([[-0.0908+0.5952j],
        [-0.3127+0.3893j],
        [ 0.4503+0.0181j],
        [ 0.4134+0.1190j]])


In [5]:
entropy = von_neumann_entropy(state1)
print(f"The von Neumann entropy between state 1 is:\n{entropy}")

traceDistance = trace_distance(state1, state2)
print(traceDistance.dtype)
print(f"The trace distance between state 1 and state 2  is:\n{traceDistance}")

fidelity = state_fidelity(state1, state2)
print(f"The state fidelity between state 1 and state 2 is:\n{fidelity}")

purity_state = purity(state1)
print(f"The purity of state 1 is:\n{purity_state}")

r_entropy = relative_entropy(state1, state2)
print(f"The relative entropy of state 1 and state 2 is:\n{r_entropy}")

p = 2
pnorm = p_norm(state1, p)
print(f"The Schatten {p}-norm of state 1 is:\n{pnorm}")

The von Neumann entropy between state 1 is:
1.6204648336221799
torch.float64
The trace distance between state 1 and state 2  is:
0.7882972615918882
The state fidelity between state 1 and state 2 is:
0.47745516931241044
The purity of state 1 is:
0.3649625962019061
The relative entropy of state 1 and state 2 is:
39.84313001423501
The Schatten 2-norm of state 1 is:
0.6041213422830766


## Validation functions
Users can use validation functions in `qinfo` to check if the matrix satisfies certain conditions.
- Check if the input matrix is a positive semi-definite matrix by `is_positive`.
- Check if the input quantum state is PPT by `is_ppt`.
- Check if the input matrix is unitary by `is_unitary`.

In [6]:
is_positive(A)
print(f"The matrix is a positive matrix: {is_positive(A)}")

is_ppt(state1)
print(f"The state 1 is a PPT state: {is_ppt(state1)}")

is_unitary(A)
print(f"The matrix is a unitary matrix: {is_unitary(A)}")

The matrix is a positive matrix: False
The state 1 is a PPT state: True
The matrix is a unitary matrix: True


## Compatibility with different data formats
Functions in `qinfo` support different formats of input, including *torch.Tensor*, *numpy.ndarray*, and *State*. The input data format is transformed through `_type_transform`. At the same time, the output format is consistent with the input format in the most situations. For example, the output will be *numpy.ndarray* format if the input is also *numpy.ndarray* format.

In [7]:
# Input with torch.tensor format
print(f"State fidelity dtype (torch.tensor): {type(state_fidelity(state1, state2))}")

# Input with numpy.ndarray format
state1_num = state1.numpy()
state2_num = state2.numpy()
print(f"State fidelity dtype (numpy.ndarray): {type(state_fidelity(state1_num, state2_num))}")

# Input with State format
state1_sta = to_state(state1)
state2_sta = to_state(state2)
print(f"State fidelity dtype (State): {type(state_fidelity(state1_sta, state2_sta))}")


State fidelity dtype (torch.tensor): <class 'torch.Tensor'>
State fidelity dtype (numpy.ndarray): <class 'numpy.ndarray'>
State fidelity dtype (State): <class 'torch.Tensor'>


---

In [8]:
qkit.print_info()


---------VERSION---------
quairkit: 0.5.1
torch: 2.11.0+cu130
torch cuda: 13.0
numpy: 2.2.6
scipy: 1.15.3
matplotlib: 3.10.5
---------SYSTEM---------
Python version: 3.10.18
OS: Linux
OS version: #1 SMP PREEMPT_DYNAMIC Thu Jun  5 18:30:46 UTC 2025
---------DEVICE---------
CPU:  13th Gen Intel(R) Core(TM) i9-13980HX
GPU: (0) NVIDIA GeForce RTX 4090 Laptop GPU
